name: Main Workflow

on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./branch.yml

  test_unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./release.yml

